### ISSUE TITLE
"agegroup" param should be "age"

### ISSUE THREAD

**Issue by adamsfallen** [accenturelabs/midaas-expanded-api#2]
agegroup does not seem to return filtered values but age does.

**Comment by mike-wendt** [comment]
You're correct it doesn't match the docs nor does it match the parameter definitions for [midaas-api](https://github.com/CommerceDataService/midaas-api) I'll close this once it is fixed

**Comment by adamsfallen** [comment]
sorry so are we going with age or agegroup? @mike-wendt

**Comment by mike-wendt** [comment]
@adamsfallen `agegroup` is the correct parameter to use
