### ISSUE TITLE
API response now has weird nesting ("overall:")

### ISSUE THREAD

**Issue by adamsfallen** [accenturelabs/midaas-expanded-api#6]
responses used to look like:
{"5%":"300","10%":"3000","20%":"8100","30%":"13500","40%":"19400","50%":"25000","60%":"31700","70%":"40000","80%":"50000","90%":"70000","95%":"92000","99%":"165000"}

now look like:
{"overall":{"5%":300,"10%":3000,"20%":8100,"30%":13500,"40%":19400,"50%":25000,"60%":31700,"70%":40000,"80%":50000,"90%":70000,"95%":92000,"99%":165000}}

Is this a bug or by design?

**Comment by mike-wendt** [comment]
By design and new docs are coming but got pulled into a meeting. Will publish asap

-Mike Wendt

**Comment by mike-wendt** [comment]
This is to match what midaas-api actually returns and for what the chart expects https://midaas.commerce.gov/developers/#widgets-bar-chart
